### ISSUE TITLE
Finalize order and purchase new PCB (Rev 2)

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-purpose-alarm-device#203]
Review the Rev 2 PCB, then order 15 new populated boards.

Also, order 5 3d printed cases.

Our goal here is to have at least 3 fully functional devices to have at the OSHWA table in April 28th in New York.

**Comment by LokiMetaSmith** [comment]
- [ ] Make modifications for louder Piezo
- [ ] Review GPAD schematic
- [ ] Review 3D printed STL files
- [ ] Review Design for Manufacturing JLCPCB
- [ ] Review gerber files
- [ ] Export gerber files
- [ ] Export STL files
- [ ] Order

**Comment by ForrestErickson** [comment]
On 20230221 Lee has fixed the pin numbering problem on the I2C connector J105 and moved J105 closer to the edge of the PCB.
As of 10 AM still reviewing issues for more actionable items.

**Comment by ForrestErickson** [comment]
Updating some silk screen locations. Run DRC and get only the expected warnings.
![image](https://user-images.githubusercontent.com/5836181/220388907-aedcd5fa-00de-4051-bcf9-30ccf71e0236.png)

**Comment by ForrestErickson** [comment]
Generated step file of the PCB produced  a large report with a lot of parts not converting.  Not a blocker but something for information only.

**Comment by RobertLRead** [comment]
Done.
