### ISSUE TITLE
GitHub Search Engine Optimization (SEO)

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-purpose-alarm-device#238]
Should we review our project on GitHub for Search Engine Optimization (SEO)?
An article here:
https://www.developermarkepear.com/blog/github-search-engine-optimization

**Comment by LokiMetaSmith** [comment]
I've updated the tags, the website https://www.pubinv.org/project/general-purpose-alarm-device-gpad/ and confirmed that the about string is accurate.
