### ISSUE TITLE
HardwareX Paper, Descirption of Design based on the SCAD Reference Design

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-purpose-alarm-device#245]
From Lee's email of 
6/25/2023 11:14 AM

The design of the enclosure should give credit to the SCAD reference design  with which Lawrence started. Lawrence can you provide details?

**Comment by ForrestErickson** [comment]
I have not seen traffic indicating that the enclosure design has been described and so I made this issue.

**Comment by LokiMetaSmith** [comment]
from the source scad file

              -  FB Aka Heartman/Hearty 2016     -                   
              -   http://heartygfx.blogspot.com    -                  
              -       OpenScad Parametric Box      -                     
              -         CC BY-NC 3.0 License

**Comment by ForrestErickson** [comment]
Lee added credits to https://github.com/PubInv/general-purpose-alarm-device/blob/main/Hardware/Enclosure/README.md

@RobertLRead IIRC you said you would add to the paper.

**Comment by LokiMetaSmith** [comment]
I've pushed the changed to the paper, per commit 92c3afa, closing as complete
