### ISSUE TITLE
Prep for Version 2 Tagged Release

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-purpose-alarm-device#246]
To release a tagged git commit we must do the following. 

- [ ] Remove references and update links from version 1 to version 2
- [ ] Update BOM for enclosure, PCB assembly, and sundry hardware as built in April 2023 (lives in manufacturing)
- [ ] Update BOM for enclosure, PCB assembly, and sundry hardware documenting the idealized release (lives in documentation)
- [ ] Reverence the tag for Version 1 and version 2 in the main document
- [ ] Verify that all firmware works for Version 2
- [ ] Add in comments on what worked and what didn't, example, (enclosure for PLA vs nylon)
- [ ] Delete unnecessary files that are Version 1 specific

**Comment by RobertLRead** [comment]
@ForrestErickson I suspect this is closable now; can you please close it if that is true?

**Comment by ForrestErickson** [comment]
Closing.
