### ISSUE TITLE
Is Their Value To Add Slicer Files?

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-purpose-alarm-device#248]
For the PolyVent Controller Card Face Plate Lee has printed parts on a Prusa 3D printer.

Is there value to adding to the repository the slicer files?
See the untracted files in Git:
![image](https://github.com/PubInv/general-purpose-alarm-device/assets/5836181/6dc21697-301f-4382-9227-fad0da3b85f3)

The particular files used for print are:
* FacePlate_FCNative_v120230622_1412_0.3mm_PLA_MK3S_26m.gcode
* FacePlate_FCNative_v120230622_1412.3mf

![image](https://github.com/PubInv/general-purpose-alarm-device/assets/5836181/7af42983-8e1a-41dd-a576-d8b68d7eee08)

**Comment by RobertLRead** [comment]
I agree with @LokiMetaSmith, I'm closing this issue.
