### ISSUE TITLE
Fill in the expected values marked TBD in manuscript in the Electrical Tests section

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-purpose-alarm-device#255]
Lee has documented things very thoroughly but there remands a 5 items marked in bold TBD s in the Electrical test area.

**Comment by ForrestErickson** [comment]
Regarding, 
Fill in the expected values marked TBD in manuscript in the Electrical Tests section #255

Please provide a URL to the document in question.

**Comment by RobertLRead** [comment]
@ForrestErickson 
https://github.com/PubInv/general-purpose-alarm-device/blob/main/doc/HardwareX%20GPAD%20Submission.odt

There is no only one TBD --- it is TBD ohms for on the line that begins "Power Jack". 

"Power Jack Measure resistance to ground at J101 center pin as greater than TBD ohms."

If you want to put it in this issue (the ohms), I will add to the paper

**Comment by ForrestErickson** [comment]
I have updated and pushed the document. No more TBDs.
