### ISSUE TITLE
Measure or state loudness of alarm

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-purpose-alarm-device#256]
I have marked a "TBD" in section 7 "Validation and characterization" to represent the loudness of the system. I think I remember Lee testing this and reporting it. We should put it in the paper. If we can't measure it, we can report the specificited rating, though a measurement is better.

**Comment by ForrestErickson** [comment]
@RobertLRead ,
I have added to the main README.md. Please close this if you find  that adequate.
