### ISSUE TITLE
As a user, I need the GPAD to have a sturdy enclosure that allows me to attach it to a medical device, such as a with zip ties.

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-purpose-alarm-device#40]

**Comment by LokiMetaSmith** [comment]
Need to add zip tie mouting hole options to the enclosure

**Comment by ForrestErickson** [comment]
Further versions will add mounting details.

**Comment by ForrestErickson** [comment]
The version 1 enclosure does not have such mounting provisions excepting perhaps through the vent slots.

**Comment by RobertLRead** [comment]
We still need this feature for the next enclosure design Enclosure 2.

**Comment by LokiMetaSmith** [comment]
We could use some solicited feedback on how people want to mount it. One way to quickly prototype would be to screw a large plate to the back of a case, and make holes where we need them to get an idea how best to add mounting holes.

**Comment by RobertLRead** [comment]
@LokiMetaSmith I don't think we should get feedback here; we should just add some holes in the enclosure for zip ties. That gives all the flexibility we need. If you disagree, let's talk about it next meeting; if you agree, let's just modify the enclosure.

**Comment by ForrestErickson** [comment]
@RobertLRead ,
@LokiMetaSmith 

Regarding the requirement for "sturdy enclosure".  The V105 enclosures are not sturdy. This. "sturdy enclosure" remains a very interesting development to under take.

**Comment by ForrestErickson** [comment]
Version 2 has been attached to a bed railing. DONE.
